[project]
name = "allenfitting"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "cellpose>=4.1.1",
    "dask>=2026.3.0",
    "matplotlib>=3.10.9",
    "napari>=0.7.0",
    "networkx>=3.6.1",
    "numpy>=2.4.6",
    "opencv-python>=4.13.0.92",
    "pandas>=3.0.3",
    "scanpy>=1.11.5",
    "scikit-learn>=1.8.0",
    "scipy>=1.17.1",
    "sdeconv>=1.0.4",
    "torch>=2.12.0",
    "tqdm>=4.67.3",
    "zarr>=3.1.6",
]
